Add socat as a dependency of the script

diff --git a/minecraft_server b/minecraft_server
--- a/minecraft_server
+++ b/minecraft_server
@@ -142,6 +142,7 @@ RSYNC=$(which rsync)
 SCREEN=$(which screen)
 WGET=$(which wget)
 RDIFF_BACKUP=$(which rdiff-backup)
+SOCAT=$(which socat)
 
 
 # Global Server Configuration
@@ -722,7 +723,7 @@ start() {
   execute "printf '' > $WORLD_DIR/response.dat" $USER_NAME
   execute "
     tail -f --pid=$PID $WORLD_DIR/query.dat | \
-    socat - UDP:127.0.0.1:$(getPropertiesValue $1 'server-port') > \
+    $SOCAT - UDP:127.0.0.1:$(getPropertiesValue $1 'server-port') > \
     $WORLD_DIR/response.dat &
   " $USER_NAME
   # Create a lock file on RedHat and derivatives.
@@ -1135,6 +1136,12 @@ if [ ! -e "$RDIFF_BACKUP" ]; then
   printf "ERROR: rdiff-backup not found!\n"
   printf "Try installing this with:\n"
   printf "sudo apt-get install rdiff-backup\n"
+  exit 1
+fi
+if [ ! -e "$SOCAT" ]; then
+  printf "ERROR: socat not found!\n"
+  printf "Try installing this with:\n"
+  printf "sudo apt-get install socat\n"
   exit 1
 fi
 
