Simplify the updateServerSoftware method

diff --git a/minecraft_server b/minecraft_server
--- a/minecraft_server
+++ b/minecraft_server
@@ -811,19 +811,14 @@ updateClientSoftware() {
 # ---------------------------------------------------------------------------
 updateServerSoftware() {
   execute "mkdir -p $SERVER_LOCATION" $USER_NAME
-  # Backup the old jar file.
-  if [ -e "$SERVER_LOCATION/$SERVER_JAR" ]; then
-    execute "mv -f \"$SERVER_LOCATION/$SERVER_JAR\" \"$SERVER_LOCATION/$SERVER_JAR.old\"" $USER_NAME
-  fi
-  # Download the new minecraft server software.
-  execute "$WGET -qO \"$SERVER_LOCATION/$SERVER_JAR\" \"$SERVER_URL\"" $USER_NAME
-  # Check for error and restore backup if found.
-  if [ $? -ne 0 ]; then
-    printf "\nError updating the Minecraft server software.\n"
-    if [ -e "$SERVER_LOCATION/$SERVER_JAR.old" ]; then
-      execute "mv -f $SERVER_LOCATION/$SERVER_JAR.old $SERVER_LOCATION/$SERVER_JAR" $USER_NAME
+  if [ ! -e "$SERVER_LOCATION/$SERVER_JAR" ]; then
+    # Download the new minecraft server software.
+    execute "$WGET -qO \"$SERVER_LOCATION/$SERVER_JAR\" \"$SERVER_URL\"" $USER_NAME
+    # Report any errors.
+    if [ $? -ne 0 ]; then
+      printf "\nError updating the Minecraft server software.\n"
+      exit 1
     fi
-    exit 1
   fi
 }
 
