Report an error if the version string is empty

diff --git a/minecraft_server b/minecraft_server
--- a/minecraft_server
+++ b/minecraft_server
@@ -532,6 +532,12 @@ getCurrentMinecraftVersion() {
   VERSION=$(
     $PERL -ne 'if ($_ =~ /^\s+\"'$TYPE'\": \"([\w\.]+)\"/) { print $1; }' $JSON
   )
+  # Print an error and exit if the version string is empty.
+  if [ -z "$VERSION" ]; then
+    printf "Error detecting the current Minecraft version.\n"
+    execute "rm -f $JSON" $USER_NAME
+    exit 1
+  fi
   echo "$VERSION"
 }
 
