Create the mirror of the level in a much more stable way
Server crashes are handled properly by doing nothing, rather than restting the world... Also, if the mirror dissapears (ramdrive + system crash) the latest backup is autmatically restored.

diff --git a/msctl b/msctl
--- a/msctl
+++ b/msctl
@@ -1017,6 +1017,7 @@ start() {
   # Make sure that the world's directory exists.
   WORLD_DIR="$WORLDS_LOCATION/$1"
   mkdir -p "$WORLD_DIR"
+  mkdir -p "$WORLD_DIR/$1"
   # Make sure the EULA has been set to true.
   EULA=$(getEULAValue "$1")
   if [ $EULA != "true" ]; then
@@ -1028,29 +1029,34 @@ start() {
   rotateLog "$1"
   # Make a mirror image of the world directory if requested.
   if [ $ENABLE_MIRROR -eq 1 ]; then
-    mkdir -p "$MIRROR_PATH/$1"
-    if [ $? -ne 0 ]; then
-      printf "Error copying world data, path %s not found.\n" $MIRROR_PATH/$1
-      exit 1
-    fi
-    # Check for a clean dismount from the previous server run.  If we have a
-    # <world>-original directory within <world> we didn't stop cleanly.
-    if [ -d "$WORLDS_LOCATION/$1/$1-original" ]; then
-      # Remove the symlink to the world-file mirror image.
-      # if recently restored from backup, this symlink may or may not exist
-      if [ -L "$WORLDS_LOCATION/$1/$1" ]; then
-        rm -r "$WORLDS_LOCATION/$1/$1"
-      fi
-
-      # Move the world files back to their original path name.
+    # Make sure the mirror master folder exists.
+    mkdir -p "$MIRROR_PATH"
+    # If the symlink exists but the target doesn't, the
+    # mirror was removed somehow. This is bad.
+    if [ -L "$WORLDS_LOCATION/$1/$1" ] && [ ! -d "$MIRROR_PATH/$1" ]; then
+      # Remove the symlink to the mirror image.
+      rm -f "$WORLDS_LOCATION/$1/$1"
+      # Restore the original world files.
       mv "$WORLDS_LOCATION/$1/$1-original" "$WORLDS_LOCATION/$1/$1"
+      # Send notification.
+      printf "Warning, the mirror for %s was removed, restored latest world.\n" $1
+    fi;
+    # If the symlink still exists, the server was stopped outside of mscs.
+    # SO DONT RESET THE MIRROR, just keep using it.
+    if [ ! -L "$WORLDS_LOCATION/$1/$1" ]; then
+      # Remove the mirror directory just in case.
+      rm -Rf "$MIRROR_PATH/$1"
+      # Copy the world files over to the mirror.
+      cp -a "$WORLDS_LOCATION/$1/$1" "$MIRROR_PATH/$1"
+      if [ $? -ne 0 ]; then
+        printf "Error copying world data, could not copy to %s.\n" $MIRROR_PATH/$1
+        exit 1
+      fi
+      # Rename the original world file directory.
+      mv "$WORLDS_LOCATION/$1/$1" "$WORLDS_LOCATION/$1/$1-original"
+      # Create a symlink from the world file directory's original name to the mirrored files.
+      ln -s "$MIRROR_PATH/$1" "$WORLDS_LOCATION/$1/$1"
     fi
-    # Copy the world files over to the mirror.
-    cp -R "$WORLDS_LOCATION/$1/$1/"* "$MIRROR_PATH/$1"
-    # Rename the original world file directory.
-    mv "$WORLDS_LOCATION/$1/$1" "$WORLDS_LOCATION/$1/$1-original"
-    # Create a symlink from the world file directory's original name to the mirrored files.
-    ln -s "$MIRROR_PATH/$1/" "$WORLDS_LOCATION/$1/$1"
   fi
   # Change to the world's directory.
   cd $WORLD_DIR
